### ISSUE TITLE
documentation seems to be ambigous in regards to 'block-device-mapping'

### ISSUE THREAD

**Issue by gretel** [atrull/ephemeral_raid_cookbook#4]
i don't get what this means:

```
When you run your instances or create your autoscaling configuration, in the following case for EC2 m1.xlarge instances, you must specify the four free emphemeral devices like so:

--block-device-mapping "/dev/xvdb=ephemeral0,/dev/xvdc=ephemeral1,/dev/xvdd=ephemeral2,/dev/xvde=ephemeral3"
```

where to pass this parameter in the context of this cookbook?

**Comment by atrull** [comment]
Hi Tom,

This is in the context of starting a machine in EC2. Those machines with instance storage never map more than the first instance store by default, so if you have 2 or more disks.. it is useful to know to look at the block device mapping function so you get all the disks to show up. Not directly related to the cookbook, but useful to understand.

I hope this makes this clear ?

**Comment by gretel** [comment]
ah i get it, thanks. comes from using `kitchen-ec2` and automated provisioning mostly. so i realize this has to be done earlier than i can :watch:

**Comment by atrull** [comment]
I'll shut this for now.
